### ISSUE TITLE
Alfred 4 incompatible

### ISSUE THREAD

**Issue by mrtnbroder** [sindresorhus/alfred-npms#26]
Hi there,

I am getting the following error when I want to install this as an Alfred 4 Workflow:

```
error /Users/mbroder/.config/yarn/global/node_modules/alfred-npms: Command failed.
Exit code: 1
Command: alfy-init
Arguments:
Directory: /Users/mbroder/.config/yarn/global/node_modules/alfred-npms
Output:
{ Error: Command failed: alfred-link
Error: `Alfred.alfredpreferences` package does not exist
    at resolveAlfredPrefs.then.then.prefsExists (/Users/mbroder/.config/yarn/global/node_modules/alfred-link/index.js:27:12)


    at makeError (/Users/mbroder/.config/yarn/global/node_modules/execa/index.js:174:9)
    at Promise.all.then.arr (/Users/mbroder/.config/yarn/global/node_modules/execa/index.js:278:16)
    at processTicksAndRejections (internal/process/task_queues.js:86:5)
  code: 1,
  stdout: '',
  stderr:
   'Error: `Alfred.alfredpreferences` package does not exist\n    at resolveAlfredPrefs.then.then.prefsExists (/Users/mbroder/.config/yarn/global/node_modules/alfred-link/index.js:27:12)\n',
  failed: true,
  signal: null,
  cmd: 'alfred-link',
  timedOut: false,
  killed: false }
info Visit https://yarnpkg.com/en/docs/cli/global for documentation about this command.
```

Would be great if we can get it to work with Alfred 4

**Comment by ifyour** [comment]
Upstream dependencies have problems and are being resolved. Detail: https://github.com/sindresorhus/alfy/issues/110

**Comment by dericgw** [comment]
Check out this comment for a temp fix: https://github.com/sindresorhus/alfy/issues/110#issuecomment-499289678

**Comment by LitoMore** [comment]
We released a patch update to fix this bug. You could rerun `npm i -g alfred-npms` to get it to work. 😄
